name: Mirror All Branches to Organization

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Mirror all branches
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Remove any existing mirror remote if present
          git remote remove mirror || true
          
          # Add organization repository as remote
          git remote add mirror https://${{ secrets.MIRROR_PAT }}@github.com/GD-LevelReqBot/gd-levelreqbot.git
          
          # Fetch all branches from source and mirror
          echo "Fetching all branches from source..."
          git fetch --all
          
          echo "Fetching existing branches from mirror..."
          git fetch mirror
          
          # List all branches before mirroring
          echo "Current local branches:"
          git branch -a
          
          echo "Current mirror branches:"
          git ls-remote --heads mirror
          
          # Push all branches and tags to mirror
          echo "Pushing all branches to mirror..."
          git push mirror --all --force
          
          echo "Pushing all tags to mirror..."
          git push mirror --tags --force
          
          # List final branches in mirror
          echo "Final branches in mirror:"
          git ls-remote --heads mirror
          
        env:
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
