name: Mirror All Branches to Organization

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MIRROR_PAT }}  # Use PAT for checkout too
          
      - name: Mirror all branches
        run: |
          # Configure Git with token-based authentication
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          
          # Remove any existing mirror remote if present
          git remote remove mirror || true
          
          # Add organization repository as remote with explicit token
          echo "Setting up mirror remote..."
          git remote add mirror "https://${{ github.repository_owner }}:${{ secrets.MIRROR_PAT }}@github.com/GD-LevelReqBot/gd-levelreqbot.git"
          
          # Fetch all branches
          echo "Fetching branches..."
          git fetch --all
          
          # Push all branches and tags
          echo "Pushing all branches..."
          git push mirror --all --force
          
          echo "Pushing all tags..."
          git push mirror --tags --force
          
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_PAT }}
