# Pushes the contents of the repo to the Codeberg mirror
name: 🪞 Mirror to GitHub
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:gd-levelreqbot/gd-levelreqbot.git
          ssh_public_key: ${{ secrets.DEPLOY_SSH }}
